/*
 * Copyright (c) Panchosoft
 * Developed by Francisco I. Leyva
 * AppSpy - http://labs.panchosoft.com/appspy
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.panchosoft.appspy.views;

import java.awt.Desktop;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.AudioInputStream;

/**
 *
 * @author Panchosoft
 */
public class AppSpyAcerca extends javax.swing.JDialog {

    javax.swing.ImageIcon icon;

    /** Creates new form AppSpyAcerca */
    public AppSpyAcerca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        icon = new javax.swing.ImageIcon(this.getClass().getResource("/com/panchosoft/appspy/resources/images/fondo_about.png"));

        FondoVista contentPane = new FondoVista();
        contentPane.setBackgroundImage(icon.getImage());
        this.setContentPane(contentPane);

        if (esMac()) {
            this.setPreferredSize(new java.awt.Dimension(507, 420));
        } else {
            this.setPreferredSize(new java.awt.Dimension(513, 420));
        }

        initComponents();
        this.setLocationRelativeTo(null);
        this.panelDescripcion.getViewport().setOpaque(false);
        this.panelAutor.getViewport().setOpaque(false);
        this.playGladosSound();
    }

    public void playGladosSound() {
        new Thread(new Runnable() {

            @Override
            public void run() {
                try {
                    Clip clip = AudioSystem.getClip();
                    java.net.URL url = new java.net.URL("http://labs.panchosoft.com/appspy/sounds/thereyouare.wav");
                    AudioInputStream inputStream = AudioSystem.getAudioInputStream(url);
                    clip.open(inputStream);
                    clip.start();
                } catch (Exception e) {
                    System.err.println(e.getMessage());
                }
            }
        }).start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen = new javax.swing.JLabel();
        lblAppSpy = new javax.swing.JLabel();
        panelDescripcion = new javax.swing.JScrollPane();
        lblDescripcion = new javax.swing.JTextArea();
        lblPaypal = new javax.swing.JLabel();
        panelAutor = new javax.swing.JScrollPane();
        lblAutorDesc = new javax.swing.JTextArea();
        lblImagen1 = new javax.swing.JLabel();
        lblPanchosoft = new javax.swing.JLabel();
        lblLinks = new javax.swing.JLabel();
        lblAppSpyWeb = new javax.swing.JLabel();
        lblPlabsWeb = new javax.swing.JLabel();
        lblPblogweb = new javax.swing.JLabel();
        lblAppSpyLink = new javax.swing.JLabel();
        lblPlabsLink = new javax.swing.JLabel();
        lblPbloglink = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About AppSpy [Beta] - Panchosoft.com Labs");
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImage((new javax.swing.ImageIcon(this.getClass().getResource("/com/panchosoft/appspy/resources/images/iconapp.png"))).getImage());
        setLocationByPlatform(true);
        setResizable(false);

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/panchosoft/appspy/resources/images/iconapp.png"))); // NOI18N
        lblImagen.setToolTipText("Visit AppSpy homepage!");
        lblImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblImagen.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagenMouseClicked(evt);
            }
        });

        lblAppSpy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/panchosoft/appspy/resources/images/appspy.png"))); // NOI18N

        panelDescripcion.setBorder(null);
        panelDescripcion.setFont(new java.awt.Font("Segoe UI", 2, 11));
        panelDescripcion.setOpaque(false);
        panelDescripcion.setPreferredSize(new java.awt.Dimension(154, 79));

        lblDescripcion.setColumns(20);
        lblDescripcion.setEditable(false);
        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 2, 11));
        lblDescripcion.setForeground(new java.awt.Color(251, 251, 251));
        lblDescripcion.setLineWrap(true);
        lblDescripcion.setRows(5);
        lblDescripcion.setText("App Spy is a little tool that lets you know technical information about your iPhone or iPod applications. Also tells you if there are any updates available for your apps, regardless if they are original or cracked.\n\nIf you like the application and would like to get new versions, I would appreciate your support through donations. :)");
        lblDescripcion.setWrapStyleWord(true);
        lblDescripcion.setOpaque(false);
        lblDescripcion.setPreferredSize(new java.awt.Dimension(150, 79));
        panelDescripcion.setViewportView(lblDescripcion);

        lblPaypal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/panchosoft/appspy/resources/images/paypal_donate.jpg"))); // NOI18N
        lblPaypal.setToolTipText("Please donate with paypal :)");
        lblPaypal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPaypal.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPaypalMouseClicked(evt);
            }
        });

        panelAutor.setBorder(null);
        panelAutor.setOpaque(false);

        lblAutorDesc.setColumns(20);
        lblAutorDesc.setEditable(false);
        lblAutorDesc.setFont(new java.awt.Font("Segoe UI", 2, 11));
        lblAutorDesc.setForeground(new java.awt.Color(251, 251, 251));
        lblAutorDesc.setLineWrap(true);
        lblAutorDesc.setRows(2);
        lblAutorDesc.setText("AppSpy is another public experiment from Panchosoft.com Labs.");
        lblAutorDesc.setOpaque(false);
        panelAutor.setViewportView(lblAutorDesc);

        lblImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/panchosoft/appspy/resources/images/javalogo.png"))); // NOI18N
        lblImagen1.setToolTipText("AppSpy is written with Java 1.6");
        lblImagen1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblPanchosoft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/panchosoft/appspy/resources/images/ps.png"))); // NOI18N
        lblPanchosoft.setToolTipText("Visit Panchosoft.com Labs");
        lblPanchosoft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPanchosoft.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPanchosoftMouseClicked(evt);
            }
        });

        lblLinks.setFont(new java.awt.Font("Segoe UI", 2, 11));
        lblLinks.setForeground(new java.awt.Color(251, 251, 251));
        lblLinks.setText("Links:");

        lblAppSpyWeb.setFont(new java.awt.Font("Segoe UI", 2, 11));
        lblAppSpyWeb.setForeground(new java.awt.Color(251, 251, 251));
        lblAppSpyWeb.setText("App Spy:");

        lblPlabsWeb.setFont(new java.awt.Font("Segoe UI", 2, 11));
        lblPlabsWeb.setForeground(new java.awt.Color(251, 251, 251));
        lblPlabsWeb.setText("Panchosoft Labs:");

        lblPblogweb.setFont(new java.awt.Font("Segoe UI", 2, 11));
        lblPblogweb.setForeground(new java.awt.Color(251, 251, 251));
        lblPblogweb.setText("Panchosoft Blog:");

        lblAppSpyLink.setFont(new java.awt.Font("Segoe UI", 3, 11));
        lblAppSpyLink.setForeground(new java.awt.Color(251, 251, 251));
        lblAppSpyLink.setText("http://labs.panchosoft.com/appspy/");
        lblAppSpyLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAppSpyLink.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAppSpyLinkMouseClicked(evt);
            }
        });

        lblPlabsLink.setFont(new java.awt.Font("Segoe UI", 3, 11));
        lblPlabsLink.setForeground(new java.awt.Color(251, 251, 251));
        lblPlabsLink.setText("http://labs.panchosoft.com/");
        lblPlabsLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPlabsLink.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPlabsLinkMouseClicked(evt);
            }
        });

        lblPbloglink.setFont(new java.awt.Font("Segoe UI", 3, 11));
        lblPbloglink.setForeground(new java.awt.Color(251, 251, 251));
        lblPbloglink.setText("http://www.panchosoft.com/blog/");
        lblPbloglink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPbloglink.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPbloglinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(205, 205, 205).addComponent(lblPaypal)).addGroup(layout.createSequentialGroup().addGap(35, 35, 35).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(lblPanchosoft).addGap(38, 38, 38).addComponent(lblImagen1).addGap(18, 18, 18).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(lblPblogweb).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(lblPbloglink)).addGroup(layout.createSequentialGroup().addComponent(lblPlabsWeb).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(lblPlabsLink)).addGroup(layout.createSequentialGroup().addComponent(lblAppSpyWeb).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(lblAppSpyLink)).addComponent(lblLinks, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(lblImagen).addGap(11, 11, 11).addComponent(lblAppSpy, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)).addComponent(panelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(panelAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE))))).addGap(49, 49, 49)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(29, 29, 29).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(lblImagen).addGroup(layout.createSequentialGroup().addGap(10, 10, 10).addComponent(lblAppSpy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(panelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(lblPaypal).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(panelAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(lblLinks).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(lblAppSpyWeb).addComponent(lblAppSpyLink)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(lblPlabsWeb).addComponent(lblPlabsLink)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(lblPblogweb).addComponent(lblPbloglink))).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(lblImagen1).addComponent(lblPanchosoft, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))).addContainerGap(48, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblPaypalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaypalMouseClicked
        // Abrimos la URL de la aplicación en iTunes
        try {
            Desktop d = Desktop.getDesktop();
            d.browse(new java.net.URI("https://www.paypal.com/cgi-bin/webscr?business=G9V2X8KXGY5JS&item_name=AppSpy%20Support&item_number=PLABS1&no_note=0&currency_code=USD&cmd=_donations"));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_lblPaypalMouseClicked

    private void lblImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagenMouseClicked
        // Abrimos la URL de la aplicación en iTunes
        try {
            Desktop d = Desktop.getDesktop();
            d.browse(new java.net.URI("http://labs.panchosoft.com/appspy/"));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_lblImagenMouseClicked

    private void lblPanchosoftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPanchosoftMouseClicked
        // Abrimos la URL de la aplicación en iTunes
        try {
            Desktop d = Desktop.getDesktop();
            d.browse(new java.net.URI("http://labs.panchosoft.com/"));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_lblPanchosoftMouseClicked

    private void lblAppSpyLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAppSpyLinkMouseClicked
        // Abrimos la URL de la aplicación en iTunes
        try {
            Desktop d = Desktop.getDesktop();
            d.browse(new java.net.URI("http://labs.panchosoft.com/appspy/"));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_lblAppSpyLinkMouseClicked

    private void lblPlabsLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlabsLinkMouseClicked
        // Abrimos la URL de la aplicación en iTunes
        try {
            Desktop d = Desktop.getDesktop();
            d.browse(new java.net.URI("http://labs.panchosoft.com/"));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_lblPlabsLinkMouseClicked

    private void lblPbloglinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPbloglinkMouseClicked
        // Abrimos la URL de la aplicación en iTunes
        try {
            Desktop d = Desktop.getDesktop();
            d.browse(new java.net.URI("http://www.panchosoft.com/blog/"));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_lblPbloglinkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                AppSpyAcerca dialog = new AppSpyAcerca(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public boolean esWindows() {

        String os = System.getProperty("os.name").toLowerCase();
        //windows
        return (os.indexOf("win") >= 0);

    }

    public boolean esMac() {

        String os = System.getProperty("os.name").toLowerCase();
        //Mac
        return (os.indexOf("mac") >= 0);

    }

    public boolean esUnix() {

        String os = System.getProperty("os.name").toLowerCase();
        //linux or unix
        return (os.indexOf("nix") >= 0 || os.indexOf("nux") >= 0);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAppSpy;
    private javax.swing.JLabel lblAppSpyLink;
    private javax.swing.JLabel lblAppSpyWeb;
    private javax.swing.JTextArea lblAutorDesc;
    private javax.swing.JTextArea lblDescripcion;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblLinks;
    private javax.swing.JLabel lblPanchosoft;
    private javax.swing.JLabel lblPaypal;
    private javax.swing.JLabel lblPbloglink;
    private javax.swing.JLabel lblPblogweb;
    private javax.swing.JLabel lblPlabsLink;
    private javax.swing.JLabel lblPlabsWeb;
    private javax.swing.JScrollPane panelAutor;
    private javax.swing.JScrollPane panelDescripcion;
    // End of variables declaration//GEN-END:variables
}
